"use client";

import { Button, Card, CardBody, CardFooter, CardHeader, Divider, Tooltip } from "@nextui-org/react";
import { AnimatePresence, motion, useInView } from "framer-motion";
import React, { useEffect, useRef, useState } from 'react';
import { toast } from "sonner";
import { generateEmoji } from '../utils/quoteGenerator';

interface QuoteCardProps {
  name: string;
  date: string;
  quote: string;
  isUnmotivational?: boolean;
  onCopy?: (text: string) => void;
}

const QuoteCard: React.FC<QuoteCardProps> = ({
  name,
  date,
  quote,
  isUnmotivational = false,
  onCopy
}) => {
  const cardRef = useRef<HTMLDivElement>(null);
  const quoteTextRef = useRef<HTMLQuoteElement>(null);
  const isInView = useInView(cardRef, { once: true });
  const [isCopied, setIsCopied] = useState(false);

  // Generate random emoji based on name and date
  const randomEmoji = generateEmoji(name, date, isUnmotivational);

  useEffect(() => {
    // Add a small delay to ensure the animation has started
    const timeoutId = setTimeout(() => {
      if (cardRef.current) {
        // Scroll the card into view with smooth behavior
        cardRef.current.scrollIntoView({
          behavior: 'smooth',
          block: 'center'
        });

        // Set focus to the card for accessibility
        cardRef.current.focus();
      }
    }, 300);

    return () => clearTimeout(timeoutId);
  }, []);

  const handleCopyQuote = () => {
    const textToCopy = `"${quote}" - Generated by Emotevation for ${name} on ${date}`;

    navigator.clipboard.writeText(textToCopy)
      .then(() => {
        setIsCopied(true);
        toast.success('Quote copied to clipboard!', {
          description: 'You can now paste it anywhere',
          duration: 3000,
        });

        // Reset the copied state after 2 seconds
        setTimeout(() => {
          setIsCopied(false);
        }, 2000);

        if (onCopy) {
          onCopy(textToCopy);
        }
      })
      .catch(err => {
        console.error('Could not copy text: ', err);
        toast.error('Failed to copy to clipboard', {
          description: 'Please try again',
        });
      });
  };

  return (
    <motion.div
      ref={cardRef}
      tabIndex={0} // Make it focusable with a logical tab order
      aria-label={`Quote for ${name}`}
      initial={{ boxShadow: "0 4px 14px 0 rgba(0, 0, 0, 0.1)" }}
      whileHover={{ boxShadow: "0 10px 25px 0 rgba(0, 0, 0, 0.2)" }}
      transition={{ duration: 0.3 }}
      className="focus-attention focus:outline-none focus:ring-2 focus:ring-secondary rounded-xl"
      onKeyDown={(e) => {
        // Allow users to copy the quote with keyboard (Enter or Space)
        if (e.key === 'Enter' || e.key === ' ') {
          handleCopyQuote();
          e.preventDefault();
        }
      }}
    >
      <Card className="max-w-xl mx-auto border-none shadow-xl">
        <CardHeader className="flex gap-3 justify-center relative pb-6 md:pb-8 pt-8 md:pt-10">
          <motion.div
            className="flex flex-col items-center"
            initial={{ y: 10, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.3 }}
          >
            <h2 className={`text-xl font-bold ${
              isUnmotivational ? 'text-default-400' : 'text-purple-600'
            }`}>
              {isUnmotivational ? 'Your Reality Check for Today' : 'Your Quote for Today'}
            </h2>

            <div className="flex flex-col items-center space-y-1 mt-2">
              <p className="text-sm font-semibold">For {name}</p>
              <p className="text-xs text-default-500">{date}</p>
            </div>
          </motion.div>
        </CardHeader>

        <Divider />

        <CardBody className="relative px-4 md:px-8 py-6 md:py-8 group">
          {/* Random Emoji in highlight above quote */}
          <motion.div
            className="flex justify-center mb-4"
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.4, type: "spring", stiffness: 200 }}
          >
            <div className={`w-24 h-24 md:w-28 md:h-28 rounded-full flex items-center justify-center text-4xl md:text-5xl ${
              isUnmotivational
                ? 'bg-gradient-to-br from-zinc-100 to-zinc-200 shadow-lg'
                : 'bg-gradient-to-br from-purple-100 to-pink-100 shadow-lg'
            }`}>
              {randomEmoji}
            </div>
          </motion.div>

          <motion.blockquote
            ref={quoteTextRef}
            className="text-lg md:text-xl italic text-center font-light leading-relaxed"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6, delay: 0.6 }}
          >
            &ldquo;{quote}&rdquo;
          </motion.blockquote>

          {/* Copy button - appears on hover/focus */}
          <AnimatePresence>
            <motion.div
              className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 focus-within:opacity-100"
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.8 }}
              transition={{ duration: 0.2 }}
            >
              <Tooltip content={isCopied ? "Copied!" : "Copy quote"}>
                <Button
                  isIconOnly
                  variant="light"
                  size="sm"
                  radius="full"
                  aria-label="Copy quote to clipboard"
                  onClick={handleCopyQuote}
                  className={`transition-all duration-200 ${isCopied ? 'bg-success-100 text-success-600' : 'bg-default-100'}`}
                >
                  {isCopied ? (
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M9 20.25L3.75 15L5.48 13.28L9 16.8L18.52 7.28L20.25 9L9 20.25Z" fill="currentColor" />
                    </svg>
                  ) : (
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M16 12.9V17.1C16 20.6 14.6 22 11.1 22H6.9C3.4 22 2 20.6 2 17.1V12.9C2 9.4 3.4 8 6.9 8H11.1C14.6 8 16 9.4 16 12.9Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                      <path d="M22 6.9V11.1C22 14.6 20.6 16 17.1 16H16V12.9C16 9.4 14.6 8 11.1 8H8V6.9C8 3.4 9.4 2 12.9 2H17.1C20.6 2 22 3.4 22 6.9Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  )}
                </Button>
              </Tooltip>
            </motion.div>
          </AnimatePresence>
        </CardBody>

        <Divider />

        <CardFooter className="flex justify-center text-center text-xs text-default-500 px-4 md:px-6 py-2 md:py-3">
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.8 }}
          >
            {isUnmotivational
              ? 'This reality check is uniquely generated for you based on your name and this date'
              : 'This quote is uniquely generated for you based on your name and this date'}
          </motion.p>
        </CardFooter>
      </Card>
    </motion.div>
  );
};

export default QuoteCard;
