"use client";

import { Button, Divider, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader } from "@nextui-org/react";
import { motion } from "framer-motion";
import React from 'react';
import { toast } from "sonner";

interface QuoteShareOptionsProps {
  isOpen: boolean;
  onClose: () => void;
  quote: string;
  name: string;
  date: string;
}

const QuoteShareOptions: React.FC<QuoteShareOptionsProps> = ({
  isOpen,
  onClose,
  quote,
  name,
  date
}) => {
  const shareText = `"${quote}" - Generated by Emotevation for ${name} on ${date}`;

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(shareText)
      .then(() => {
        toast.success('Quote copied to clipboard!');
        onClose();
      })
      .catch(() => {
        toast.error('Failed to copy to clipboard');
      });
  };

  const handleShareViaSystem = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Emotevation Quote',
          text: shareText,
          url: window.location.href,
        });
        toast.success('Quote shared successfully!');
        onClose();
      } catch (error) {
        console.error('Error sharing:', error);
        toast.error('Failed to share quote');
      }
    } else {
      handleCopyToClipboard();
    }
  };

  const handleShareViaTwitter = () => {
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(window.location.href)}`;
    window.open(twitterUrl, '_blank');
    toast.success('Sharing to Twitter');
    onClose();
  };

  const handleShareViaFacebook = () => {
    const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}&quote=${encodeURIComponent(shareText)}`;
    window.open(facebookUrl, '_blank');
    toast.success('Sharing to Facebook');
    onClose();
  };

  const handleShareViaEmail = () => {
    const emailUrl = `mailto:?subject=${encodeURIComponent('My Emotevation Quote')}&body=${encodeURIComponent(`${shareText}\n\nGenerated at: ${window.location.href}`)}`;
    window.open(emailUrl, '_blank');
    toast.success('Opening email client');
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} backdrop="blur">
      <ModalContent>
        {(onClose) => (
          <>
            <ModalHeader className="flex flex-col gap-1">
              <motion.h3
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
                className="text-xl font-bold"
              >
                Share Your Quote
              </motion.h3>
              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3, delay: 0.1 }}
                className="text-sm text-default-500"
              >
                Choose how you want to share your quote
              </motion.p>
            </ModalHeader>

            <ModalBody>
              <div className="flex flex-col gap-3">
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 0.2 }}
                  className="p-3 rounded-lg bg-default-100 italic text-center text-sm"
                >
                  "{quote}"
                </motion.div>

                <Divider className="my-2" />

                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 0.3 }}
                  className="grid grid-cols-2 gap-3"
                >
                  <Button
                    color="secondary"
                    className="w-full"
                    startContent={
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M16 12.9V17.1C16 20.6 14.6 22 11.1 22H6.9C3.4 22 2 20.6 2 17.1V12.9C2 9.4 3.4 8 6.9 8H11.1C14.6 8 16 9.4 16 12.9Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                        <path d="M22 6.9V11.1C22 14.6 20.6 16 17.1 16H16V12.9C16 9.4 14.6 8 11.1 8H8V6.9C8 3.4 9.4 2 12.9 2H17.1C20.6 2 22 3.4 22 6.9Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    }
                    onClick={handleCopyToClipboard}
                  >
                    Copy
                  </Button>

                  <Button
                    color="success"
                    className="w-full"
                    startContent={
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M7.4 6.32L15.89 3.49C19.7 2.22 21.77 4.3 20.51 8.11L17.68 16.6C15.78 22.31 12.66 22.31 10.76 16.6L9.92 14.08L7.4 13.24C1.69 11.34 1.69 8.23 7.4 6.32Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                        <path d="M10.11 13.65L13.69 10.06" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    }
                    onClick={handleShareViaSystem}
                  >
                    Share
                  </Button>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 0.4 }}
                  className="grid grid-cols-2 gap-3"
                >
                  <Button
                    color="primary"
                    variant="flat"
                    className="w-full"
                    onClick={handleShareViaTwitter}
                  >
                    Twitter
                  </Button>

                  <Button
                    color="primary"
                    variant="flat"
                    className="w-full"
                    onClick={handleShareViaFacebook}
                  >
                    Facebook
                  </Button>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 0.5 }}
                >
                  <Button
                    color="default"
                    variant="flat"
                    className="w-full"
                    startContent={
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M17 20.5H7C4 20.5 2 19 2 15.5V8.5C2 5 4 3.5 7 3.5H17C20 3.5 22 5 22 8.5V15.5C22 19 20 20.5 17 20.5Z" stroke="currentColor" strokeWidth="1.5" strokeMiterlimit="10" strokeLinecap="round" strokeLinejoin="round"/>
                        <path d="M17 9L13.87 11.5C12.84 12.32 11.15 12.32 10.12 11.5L7 9" stroke="currentColor" strokeWidth="1.5" strokeMiterlimit="10" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    }
                    onClick={handleShareViaEmail}
                  >
                    Email
                  </Button>
                </motion.div>
              </div>
            </ModalBody>

            <ModalFooter>
              <Button color="danger" variant="light" onPress={onClose}>
                Cancel
              </Button>
            </ModalFooter>
          </>
        )}
      </ModalContent>
    </Modal>
  );
};

export default QuoteShareOptions;
